- icon-find.c
- icon-find.h
- icon.c
- jgmenu-cache.sh
- jgmenu.c
Benchmarks for `jgmenu pmenu` without a cache:
Remove cache:
```
rm -rf ~/.local/share/icons/jgmenu-cache
```
Old version:
```
git checkout 19fb4f0
make clean ; make ; make install
sudo sh -c 'echo 3 > /proc/sys/vm/drop_caches; for d in /dev/sd* ; do hdparm -F $d ; done'
time jgmenu_run pmenu --die-when-loaded
warning: jgmenu icon-cache has not been created
Failed to load XPM file: /opt/eclipse/icon.xpm
jgmenu_run pmenu --die-when-loaded  0.28s user 1.16s system 82% cpu 1.753 total
strace -f jgmenu_run pmenu --die-when-loaded 2>&1 | grep -E 'open|stat|access|link' | wc -l
57141
```
New version:
```
git checkout 79ce8b0
make clean ; make ; make install
sudo sh -c 'echo 3 > /proc/sys/vm/drop_caches; for d in /dev/sd* ; do hdparm -F $d ; done'
time jgmenu_run pmenu --die-when-loaded
warning: …
```
> Optimize icon lookup

- jgmenu-parse-pmenu.py
Fixed two crashes on a system where the locale was not set, so the default encoding was ASCII instead of UTF-8.
> Pmenu fixes

- scripts/create_desktop_file.sh
I've updated the desktop entry with generic name and comment, also with Russian l10n.
What are extended fields for? One is some GNOME stuff, and what's the other?
> Improve desktop entry

- debian/control
- debian/rules
NO_LX detection made superfluous in 473cacd44878e8791de8e618e94a121caa07e190.
> debian: Reflect recent changes in build system

- debian/rules
Because the makefile system's 'clean' target relies on dependencies being
installed which are not in a minimal Debian system by way of pkg-config
invocations, even without compiling, the pdebuild routines will fail (it is an idiotic choice, but
pdebuild executes the dh_auto_clean target on the host it is invoked by, not inside
the build chroot).
Override dh_auto_clean to be a noop as a workaround as redoing the makefile
system is a larger task.
Additionally, export distro build flags.
---
Error:
$ sudo pdebuild --buildresult ../stretch-backports-amd64/  --pbuildersatisfydepends /usr/lib/pbuilder/pbuilder-satisfydepends-aptitude --debbuildopts  -sa -- --basetgz /var/cache/pbuilder/stretch_amd64.tgz   ; s
udo pdebuild --buildresult ../stretch-backports-i386/  --pbu
ildersatisfydepends …
> debian/rules: omit broken dh_auto_clean target (and add some buildflags)

- src/x11-ui.c
Calling `XRRGetScreenResources()` pulls for hardware changes which on some systems freezes the screen for a few hundred milliseconds, so use `XRRGetScreenResourcesCurrent()` instead to avoid that.
I don't know if this has any other side effects but it seems to work fine for me!
> x11-ui.c: Don't pull for XRandR hardware changes

- src/xdgdirs.c
This patch enabled me to run jgmenu on FreeBSD.
> add /usr/local/etc/xdg to paths

- debian/control
- debian/jgmenu-xfce4-panel-applet.install
Changes in v4.2.0 have left behind the packaging in /debian, causing package builds to fail. Here are the fixes that allow the package to build successfully again. For the commits that introduced the problems in the first place, see the respective commit messages.
> Debian packaging fixes for v4.2.0

- contrib/unicode-icons/jgmenu-unicode-icons.sh
Just recently I discovered that jgmenu supports Pango formatting. This gives much more customization options. For example, instead of regular graphical icons (from themes or custom images in SVG or PNG format), it's possible to use hand-picked Unicode glyphs (from Font Awesome and the like) acting as icons, with their size and alignment being separated from actual labels.
This PR adds a template script that makes it easy to generate such a menu. I hope someone finds it useful.
Personally, I'm using this approach with Line Awesome font, and the result is quite nice.
> Add jgmenu-unicode-icons.sh

- contrib/gtktheme/jgmenu-gtktheme.py
Add title colours to match main menu, taken from *theme_text_color* and *background-color*.
This is a compromise, but at least gives titles that blend with the GTK theme.
> jgmenu-gtktheme.py: match title colours with main menu

- src/jgmenu.c
There is a small typo in src/jgmenu.c.
Should read `respond` rather than `repsond`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: fix simple typo, repsond -> respond

- src/desktop.c
- src/desktop.h
- src/jgmenu-apps.c
Adds support for pulling the working directory out of desktop files and passing it along.
Code should be pretty self-explanatory.
> Working directory support for jgmenu-app

- contrib/gtktheme/jgmenu-gtktheme.py
- docs/notes_on_icons
- src/cache.c
- src/cache.h
- src/icon.c
- src/jgmenu-init.sh
- tests/t1201-lx.t
> Use XDG_CACHE_HOME.

- src/jgmenu-apps.c
Enclose names/generic-names with """ so that commas are treated as part of the name rather than as separate CSV fields.
Fixes issue #192
Reported-by: @PPC-scripts
> jgmenu-apps: handle (generic) name containing commas

- contrib/xfce4-panel/jgmenu-applet.c
Presumably due to header file reorganization,
XFCE_PANEL_PLUGIN_REGISTER(jgmenu_construct);
did not have any effect anymore because the macro is not defined in <libxfce4panel/xfce-panel-plugin.h> anymore.  Current GCC version parse this line as a declaration of a function called XFCE_PANEL_PLUGIN_REGISTER with an implicit int return type and without a parameter list/prototype, which is the reason why this did not result in a compilation error.
Related to:
* https://fedoraproject.org/wiki/Changes/PortingToModernC
* https://fedoraproject.org/wiki/Toolchain/PortingToModernC
> contrib: Fix xfce4-panel registration

- INSTALL.md
- Makefile
- Makefile.inc
- configure
- src/icon.c
- src/x11-ui.h
This moves librsvg dependency to optional with a configure `--disable-svg`.
Fixes #195.
> Move librsvg dependency to optional

- Makefile.inc
...to avoid warning:
```
CC    jgmenu.o
In file included from src/x11-ui.h:11,
from src/jgmenu.c:27:
/usr/lib/pkgconfig/../../include/librsvg-2.0/librsvg/rsvg.h:1331:1: warning: this use of "defined" may not be portable [-Wexpansion-to-defined]
1331 | #if LIBRSVG_CHECK_FEATURE(PIXBUF)
| ^~~~~~~~~~~~~~~~~~~
CC    x11-ui.o
```
> build: add -Wno-expansion-to-defined

- docs/manual/jgmenu.1.md
Explicitly document the non-standard approach to quoting used by `jgmenu`
> Usage of quotes in jgmenu CSV flavour

- src/jgmenu.c
...search results.
For example with the csv data below - where the commas at the end force an empty command - we want a search for "aa" to render two results rather than one.
```
a,
aa,
aaa,
b,
bb,
bbb,
```
Fixes: #227
> jgmenu: ignore entries with empty commands when de-duplicating

- docs/manual/jgmenu.1
- docs/manual/jgmenu.1.md
- src/config.c
- src/config.h
- src/jgmenu-config.c
- src/jgmenu.c
...to that the default '<empty>' can be overridden.
Issue: #232
> config: add search_empty_string

- src/jgmenu-ob.c
For example:
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE openbox_config [
<!ENTITY image_viewer "imv">
]>
<openbox_menu>
<menu id="root-menu" label="root-menu">
<item label="View Screenshot">
<action name="Execute">
<command>&image_viewer; screenshot.png</command>
</action>
</item>
</menu>
</openbox_menu>
Related-to: #229
Cc: @Dupond
> jgmenu-ob: support xml !ENTITY definitions
